## file: /Users/tylermontgomery/.fbomb/config.yml
#

campfire:
  domain: ENV['CAMPFIRE_ACCOUNT'] 
  token:  ENV['CAMPFIRE_TOKEN'] 
  room:   ENV['CAMPFIRE_ROOM']

commands:
  - /app/commands.rb
  - system
  - builtin
